# Generated by Django 5.1.1 on 2024-10-01 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_course_author_course_author_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_image',
            field=models.ImageField(default='path/to/default_image.jpg', upload_to='courses/'),
            preserve_default=False,
        ),
    ]
